### ISSUE TITLE
Add Version Tagging

### ISSUE THREAD

**Issue by PolarLava** [shyim/adminerevo-docker#3]
I really appreciate that you've created a docker image for AdminerEvo as that makes life much easier for those of us who prefer to use docker.  My only issue is that I use atomic versioning and have another app that monitors for updates to my various containers.  Unfortunately, this project only has a "latest" tag and no version tags like the main project.  Right now that is v4.8.4, but when it updates I won't see that change because the tag here is always "latest".  Thus, would it be possible for you to add tagging that corresponds to the main project when you release an update?

**Comment by shyim** [comment]
done :)
https://github.com/shyim/adminerevo-docker/pkgs/container/adminerevo/242467899?tag=4.8.4

both on ghcr and docker hub
