### ISSUE TITLE
MSSQL returns no extension

### ISSUE THREAD

**Issue by bl4ko** [shyim/adminerevo-docker#7]
When trying to login into a MSSQL database a No extension error is thrown by adminer-evo:

```bash
None of the supported PHP extensions (SQLSRV, MSSQL, PDO_DBLIB) are available.
```

This works with adminer.

**Comment by shyim** [comment]
added the extension and triggered rebuild https://github.com/shyim/adminerevo-docker/actions/runs/12431183619
